### PR TITLE
Add left-truncation support for Random Survival Forests.

### PR DESCRIPTION
**Pull request by llpamies**
This bulk of this work was done by Francisco Maturana Sanguineti from CMU.

- [X ] py.test passes
- [X] tests are included
- [X] code is well formatted

This change allows to fit random survival forests (and survival trees) using data that can be left-truncated.

### CODE REVIEW

**Comment by sebp** [comment]
Thanks for helping to improve scikit-survival.

Could please explain a little bit more about your implementation? In particular
- Is it based on a particular paper?
- Is there a reference implementation, e.g. in R?
- How did you extend the current `y` array to account for time of entering a study?

In addition, several tests are currently failing, which should be fixed before I take a closer look.

**Comment by sebp** [comment]
@llpamies Are planning to working on this? Otherwise, I will close this PR.

**Comment by llpamies** [comment]
Yes we are still working on this. Give us a few more weeks to sort out what is going on. Thanks!

**Comment by sebp** [comment]
I'm closing this PR as no further process has been made. Feel free to re-open it if you want to continue working on it.

**Pull request closed without merging**
