### PR TITLE
[DOC] fix `GradientBoostingSurvivalAnalysis` docstring on `criterion` parameter

### PR DESCRIPTION
**Pull request by fkiraly**
Fixes https://github.com/sebp/scikit-survival/issues/448, under the assumption that the issue is with the docstring, not the logic.

### CODE REVIEW

**Review by sebp — CHANGES_REQUESTED** [review]
Thanks for noticing!

For consistence with sklearn, and to make it easier to track changes, I'd prefer to copy the API doc from sklearn. This would also remove "mae", which isn't supported by `BaseGradientBoosting`.

https://github.com/scikit-learn/scikit-learn/blob/f07e0138bfee41cd2c0a5d0251dc3fe03e6e1084/sklearn/ensemble/_gb.py#L1159-L1164

**Comment by fkiraly** [comment]
of course, done

**Comment by fkiraly** [comment]
> Thanks for noticing!

PS, it was actually the tests in `skpro` that noticed.

**Comment by sebp** [comment]
@fkiraly Thank you. Merged in commit f5e7c04

**Comment by fkiraly** [comment]
... why did you close this and merge a copy??

**Comment by sebp** [comment]
I squashed your commits before merging.

**Pull request closed without merging**
