### PR TITLE
Remove version on osqp, set min version on pandas

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
## Motivation

I am packaging this python package for Nix. See https://github.com/NixOS/nixpkgs/pull/82410

## Notes

Using those modifications I have successfully built and tested the package using Nix.

Althought it is clear to me that if those restrictions where placed here, it was for a reason.
Please let me know if something was missed.

### CODE REVIEW

**Comment by sebp** [comment]
Thanks for your patch.

Version 0.6.0 and 0.6.1 of OSQP need to remain disallowed, because they 
are unusable, see commit 3337e2789d9fc4aa14512ca2d07c1102710689c7

**Comment by GuillaumeDesforges** [comment]
@sebp do you mean that it is an error on the osqp side, another requirement of this package, or something that could be fixed inside this package ?

**Comment by sebp** [comment]
It's an issue in osqp itself, which they have fixed in later versions.

**Comment by GuillaumeDesforges** [comment]
Ok I will update osqp on Nixpkgs then. Thanks

**Pull request closed without merging**
